version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE_1
      - MYSQL_PASSWORD:$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
       - ./data/db:/var/lib/mysq
      - "./data/sql:/docker-entrypoint-initdb.d"
    networks:
      - backend
    restart: always

  backend:
    depends_on:
      - mysqldb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
    - ConnectionStrings__DefaultConnection=server=mysqldb;port=MYSQLDB_DOCKER_PORT;database=${$MYSQLDB_DATABASE_1?:};user=${MYSQLDB_USER?:};password=${MYSQLDB_ROOT_PASSWORD?:}
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
