version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    command: --max-allowed-packet=67108864
    environment:
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_PASSWORD:$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./data/db:/var/lib/mysq
      - ./data/sql:/docker-entrypoint-initdb.d
    restart: always

  backend:
    tty: true
    depends_on:
      - mysqldb
    build:
       context: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - ConnectionStrings__DefaultConnection=server=mysqldb;port=MYSQLDB_DOCKER_PORT;user=${MYSQLDB_USER?:};password=${MYSQLDB_ROOT_PASSWORD?:}
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    links:
      - mysqldb

volumes:
  db:
