export const fields_search = [
    {
        id: "external_id",
        type: "text",
        name: "External Id",
        placeholder: "ID",
        sqlOp: "where",
        op: "eq",
    },
    {
        id: "rent",
        type: "range",
        name: "rent",
        placeholder: "rent",
        sqlOp: "where",
        op: "like",
    },
    {

        name: 'Address',
        id: 'address',
        type: 'text',
        placeholder: "ID",
        sqlOp: "where",
        op: "like",
    },
    {
        name: 'Postal Code',
        id: 'postalCode',
        type: 'text',
        placeholder: "ID",
        sqlOp: "where",
        op: "like",
    },
    {
        name: 'City',
        id: 'city',
        type: 'text',
        placeholder: "ID",
        sqlOp: "where",
        op: "like",
    },
    {
        name: 'Area (m2)',
        id: 'areaSqm',
        type: 'text',
        placeholder: "ID",
        sqlOp: "where",
        op: "eq",
    },
    {
        name: 'Deposit',
        id: 'deposit',
        type: 'range',
        placeholder: "ID",
        sqlOp: "where",
        op: "eq",
    },
    {
        name: 'Room active',
        id: 'isRoomActive',
        type: 'checkbox',
        placeholder: "ID",
        sqlOp: "where",
        op: "eq",
    },
    {
        name: 'Order: Ascending ',
        id: 'order_asc',
        type: 'checkbox',
        placeholder: "ID",
        sqlOp: "order",
    },
    {
        name: 'Order: Descending ',
        id: 'order_desc',
        type: 'checkbox',
        placeholder: "ID",
        sqlOp: "order",
    },
    {
        name: 'Limit ',
        id: 'limit',
        type: 'checkbox',
        placeholder: "ID",
        sqlOp: "limit",
    },
];
